title: Code Wiz
description: Docs for Code Wiz coaches
theme: just-the-docs


url: https://docs.smartkidsllc.com

color_scheme: dark

aux_links:
  Toggle Theme: "javascript:jtd.setTheme(jtd.getTheme() == 'dark' ? 'light' : 'dark')"