title: SmartKids Docs
description: Docs for SmartKids employees
theme: just-the-docs


url: https://docs.smartkidsllc.com

color_scheme: dark

aux_links:
  Toggle Theme: "javascript:jtd.setTheme(jtd.getTheme() == 'dark' ? 'light' : 'dark')"